### ISSUE TITLE
Check-Out Command UI

### ISSUE THREAD

**Issue by Anthony1234567** [Anthony1234567/CECS543_Project-1#23]
The check-out ability lets a user recreate a specific version (snapshot) of the project tree.  They do this by selecting a particular manifest file in the repo, as an argument.   Of course, a manifest file specifies every version of every file from a particular version of a project tree.  Note that a given repo folder only deals with one project (e.g., snapshots only for the Skyrocket project, or the Red-Bunny project, or the Halo project), but the repo can contain many versions (snapshots) of that one project.  A snapshot can be created by anyone who has previously checked out a version of that project (but you donot have to verify this).  On check-out, the recreated project tree is installed in an empty folder, which the user also selects as a second argument.   We can assume that the target folder is empty.  The check-out command also creates a new manifest file, of the checked out version, in the repo.  The user should be able to specify the manifest file using a label, if it has one.

**Comment by Anthony1234567** [comment]
For check-out, the user supplies the repo folder name an empty target folder name and selects a manifest (representing the specific version of the project files desired).  The selection can be either a label or the manifest filename.  New issues must be handled:
1. You will create a new project tree inside the empty target folder.  The files copied from the repo must be those mentioned in the selected manifest.
2. Each needed repo file has an artifact ID as its filename and sits in a sub-folder that is named with its project's filename.  This repo artifact file will get copied into the empty target folder's new project tree in the correct position and with its project filename.  For example, we should be able to recreate a project tree if we executed the command sequence:a. Create-repob. Accidentally destroy/remove our project treec. Check-out to old now-empty project-tree folder by selecting the repo's creation manifest
3. Also, you will create a "check-out" manifest file for this command.  It will include the check-out command and its arguments as well as the date and time and a line for each file checked out (just like the create-repo manifest).

**Comment by sotheanithsok** [comment]
#37
