### ISSUE TITLE
Check-In Command UI

### ISSUE THREAD

**Issue by Anthony1234567** [Anthony1234567/CECS543_Project-1#24]
The check-in ability lets the user update the repository (repo) with new version (snapshot) of the project; meaning you have to add into the repo any changed files in the project tree.  So, each check-in is a (potentially) different "version" of the project tree, and you create for it a new manifest file.  This allows the user to track the modification history from a given project tree back, through various project versions, all the way to the repo's creation.  Note that we assume labels are forever (the user doesn't remove a label).   The folder containing a version of the project tree that the user specifies as an argument to the check-in command should have earlier been the target of a check-out command, and we will assume that this is always true.  Therefore, in the repo's manifest files, we can trace from a given check-in (from a user's folder) back to the original check-out into that user's folder from a snapshot of some other user's project tree in some other folder, etc., all the way back to the original create-repo command.  Note that your manifest files should reflect this ability, as it will be needed later.

**Comment by Anthony1234567** [comment]
Note that almost all of the check-in code has already been developed for the previous Create Repo project part.  A few new issues must be handled:
1. For a newer version of a file (with the same project folder relative path) as a file in the repo, the leaf folder will already exist with an earlier version of that file having a different artifact ID.You merely have to add the newer version file into the same leaf folder with its own artifact ID name.
2. If a project file has the same computed artifact ID (and project folder relative path) as a file in the repo, then we can presume that it is the same file in both placed.  So, you need not use this project file to overwrite the existing identical copy in the repo; but you can do such an overwrite if that seems easier.
3. Also, you will create a "check-in" manifest file for this command.  It will include the command and its arguments as well as the usual manifest information (same as for a "create-repo" command.)  Note, if your project #1 manifest didn't include the "create-repo" command and arguments that was used to create it, please upgrade so that that manifest includes these.
4. Regardless of whether a project file has been changed (ie, new artifact ID) or not (ie, old duplicate artifact ID), the file-name and its artifact ID must be recorded in a new manifest file for this check-in (with the check-in command line arguments and the date-time stamp, of course).

**Comment by sotheanithsok** [comment]
#37
