### ISSUE TITLE
Generate Artifact ID

### ISSUE THREAD

**Issue by Anthony1234567** [Anthony1234567/CECS543_Project-1#3]
Take in file/string(contents of file)

**Weighted checksum**: The code name will be a rolling multi-byte weighted checksum of all the
characters (bytes) in the file followed by a hyphen and an “L” and the integer file size, followed by the
file's extension. The weights by which each character in a group are multiplied are 1, 7, 3, 7, and, 11.
Thus, if the file contents is "HELLO WORLD", the checksum S is:
 `S = 4540 = 1*H + 7*E +3*L +7*L + 11*O + 1*' ' + 7*W + 3*O + 7*R + 11*L + 1*D;`
and the file size is 11. (Note, the ASCII numeric value of each character is used and we indicated the
space character by ' '.) For this version of the source file fred.txt, the AID code name would be
“4540-L11.txt”, in a leaf folder named “fred.txt”.
**Modulus**: Because the sum can get rather large for a big file, make sure the sum never gets too large
by wrapping it using the following prime modulus operator: m == (2^31) - 1 == 2,147,483,647.

**Comment by sotheanithsok** [comment]
completed #13
