### ISSUE TITLE
Recursive Walk directory

### ISSUE THREAD

**Issue by Anthony1234567** [Anthony1234567/CECS543_Project-1#4]
Generate UML Diagram
~
If new (no .git/.vcs file found):
- For each file, replace with folder. Place file in new folder
- File name = Call generate Artifact ID results (append -L<byte_size_of_file>)

Update:
- For each file Call generate Artifact ID and compare to latest artifact (can use name to do comparison)

**Comment by sotheanithsok** [comment]
Complete #12
