### ISSUE TITLE
HTML for controlling and routing

### ISSUE THREAD

**Issue by Anthony1234567** [Anthony1234567/CECS543_Project-1#6]
Create a beautiful UI to display all files from the root directory.
There a two operation that the HTML controller should perform, create and commit. For both operations, a user must provide paths to two locations, source and target. All data sent to the backend should be formatted in JSON. 

- Create: A client will make a HTTP request to the server. There are two possibilities of error. The first one is when the target path doesn't exist. The second error is when a repository already existed at the source folder.
- Commit: A client will make a HTTP request to the server. There is one possibility of error which will occur if no repository is found at the target path. 

There should be alerts to inform users if the operation that he or she performs is successfully executed or is there an error that occurs.  Any alerts must be unambiguous. Also please don't make the user works hard.

**Comment by sotheanithsok** [comment]
Completed #17 #
